#!/bin/bash 

# BY: @NNNNH
# CH : @TH3VICTORY
# TW : @ramixnxx_Bot
# Bot : @DEVRAMI_BOT
# 𝑨𝒅𝒅𝒆𝒅 𝑺𝒐𝒖𝒓𝒄𝒆 𝑩𝒚 𝑹𝑨𝑴𝑰 𝑨𝑳 𝑨𝑳𝑰
#---------------------------------------------------------------------
cd $(cd $(dirname $0); pwd)
 
RED='\033[0;31m'
SMAY='\033[0;36m' 
GREEN='\033[0;32m'
Yellow='\033[0;33m'
LSAMAY='\033[01;49m'
WHITB='\033[01;90m'
WHITEC='\033[01;91m'
CNIL='\033[0m'
Version=`lsb_release -rs | cut -f1 -d"."`

if [ "$Version" == "18" ];then
echo -e "${GREEN}
 BY: @NNNNH
 CH : @TH3VICTORY
 TW : @ramixnxx_Bot
 Bot : @DEVRAMI_BOT
 𝑨𝒅𝒅𝒆𝒅 𝑺𝒐𝒖𝒓𝒄𝒆 𝑩𝒚 𝑹𝑨𝑴𝑰 𝑨𝑳 𝑨𝑳𝑰
 ---------------------------------------------------------------------${CNIL}"
echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
${CNIL}";
echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source Rambo 
${CNIL}";
exit;
fi

CPUPer=`top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $4}' | cut -f1 -d"."`
if [[ $CPUPer -gt 90 ]]; then
echo -e "${SMAY}\n"
echo -e " BY: @NNNNH 
echo -e " CH : @TH3VICTORY 
echo -e " TW : @ramixnxx_Bot 
echo -e " Bot : @DEVRAMI_BOT
echo -e " url site : th3victory.github.io   
echo -e " 𝑨𝒅𝒅𝒆𝒅 𝑺𝒐𝒖𝒓𝒄𝒆 𝑩𝒚 𝑹𝑨𝑴𝑰 𝑨𝑳 𝑨𝑳𝑰 
echo -e " CH2 : @RAMBO_SYR 
echo -e " MY BRO : @ZJJJJ
echo -e " ---------------------------------------------------------------------"
echo -e "${CNIL}"
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Cpu is load full > 90% .
¦ Please clean your Work in ${Yellow}You Server ${WHITB}And Run Again${SMAY} Source RAMBO${CNIL} . \n
\n\n"
exit;
fi

if [ ! -f "./TG" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Not Dwonload TG .
¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source RAMBO${CNIL} . \n
\n\n"
chmod +x ./ins
./ins
exit;
fi

if [ ! -f "./inc/Token.txt" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Token Bot Not Found .
¦ NOW I Run File ${SMAY}./RUN.lua${WHITB} To Enter Data For You Bot${CNIL}. \n
\n\n"
lua ./inc/Run.lua
exit;
else
TOKEN=`cat ./inc/Token.txt`
BOTID=`echo $TOKEN | cut -f1 -d":"`
Check=`redis-cli ping`
if [[ $Check == "" ]]; then
echo -e "${RED}
¦ CAUTION:${WHITB} Rides is Not Working .
¦ Please Run Redis From This Command ${SMAY}service redis-server start${WHITB} . \n
\n\n"
exit;
fi

Sudo=`redis-cli get ${BOTID}:SUDO_ID:`
if [[ $Sudo == "" ]]; then
echo "sudo is empty"
rm -fr ./inc/Token.txt
lua ./inc/Run.lua
exit;
fi

fi


chmod +x ./TG  
Loops=0
if [ "$1" == "R" ]; then
while [[ $Loops -le 5 ]]; do
sleep 1s
sudo rm -fr ~/.telegram-cli
./TG -s ./inc/Run.lua --bot=$TOKEN
let Plas=Loops+1
Check=`redis-cli ping`
if [[ $Check == "" ]]; then
Loops=6
else
redis-cli SETEX $TOKEN 3 $Plas
Loops=`redis-cli GET ${TOKEN}`
echo $Loops
if [[ $Loops == 5 ]]; then
curl "https://api.telegram.org/bot${TOKEN}/sendmessage" -F "chat_id=${Sudo}" -F "text=THESOURCE-Reloaded-${COUNTER}-times" &>/dev/null
screen -X -S rbot quit
fi
fi
done
else 
if [[ $Loops == 0 ]]; then
if ! screen -list | grep -q "rbot"; then
screen -S rbot ./run R
else
screen -X -S rbot quit
screen -S rbot ./run R
fi
fi
fi

